version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g prisma
  build:
    commands:
      - echo "Building Next.js app..."
      - npx prisma generate
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
  discard-paths: no
