version: 0.2

env:
  variables:
    NODE_ENV: "production"
  # Optional but recommended: speeds up builds by reusing node_modules
  cache:
    paths:
      - 'node_modules/**/*'

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "🚀 Installing dependencies..."
      - npm ci
      - npm install -g prisma
  pre_build:
    commands:
      - echo "🧠 Generating Prisma client..."
      - npx prisma generate
  build:
    commands:
      - echo "🏗️ Building Next.js app..."
      # Disable lint blocking build
      - echo "Disabling ESLint blocking in build..."
      - |
        if [ -f next.config.js ]; then
          if ! grep -q "ignoreDuringBuilds" next.config.js; then
            echo "Adding eslint.ignoreDuringBuilds flag to next.config.js..."
            sed -i "s/module.exports = {/module.exports = { eslint: { ignoreDuringBuilds: true },/" next.config.js
          fi
        fi
      - npm run build --no-lint
  post_build:
    commands:
      - echo "✅ Build completed successfully."
      - echo "Preparing artifact for deployment..."
      # Clean up unnecessary files (optional optimization)
      - rm -rf node_modules/.cache
      - rm -rf .git

artifacts:
  files:
    - '**/*'
  discard-paths: no
